language: java
rvm:
 - 2.2
 - jjava
addons:
  sonarcloud:
    organization: "rayton69"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ipi-java-350-ex1
